### ISSUE TITLE
Auto Update LSP on Startup seems to be ignored.

### ISSUE THREAD

**Issue by crashmeister** [albilu/netbeansPython#101]
When I start Netbeans (v19) and open a python source file, the configuration I have set up is not implemented.
I have to open settings, add a space to the config somewhere to trick it into thinking it has been updated, the click 'Apply'.
At this point my config works. Opening another files shows correct implementation of the config. When I quit Netbeans, the config is lost.

I should NOT have to do this every time I open Netbeans. My config should be applied automatically.

**This shows all the code marked with violations after opening Netbeans:**

![Screenshot 2024-02-03 at 12 18 55](https://github.com/albilu/netbeansPython/assets/58121863/2ec026cc-d2c1-49a9-b458-62d0ce9747d1)

**This shows the LSP Server tab in Netbeans Settings, Auto Update is checked:**

![Screenshot 2024-02-03 at 12 19 54](https://github.com/albilu/netbeansPython/assets/58121863/0d4d9865-98c6-4401-9eed-4018e21b9a39)

**This shows the same code correctly displayed after applying a dummy 'space' change to the config:**

![Screenshot 2024-02-03 at 12 20 34](https://github.com/albilu/netbeansPython/assets/58121863/c9fff6fe-ef13-497a-bea7-61dd08fa58b7)

Thanks.
Craig.

**Comment by albilu** [comment]
@crashmeister Make sure your configuration is correct. From the screenshot i can already tell it is not: maxLineLenght must be number not string.
Make sure the config follow https://github.com/python-lsp/python-lsp-server?tab=readme-ov-file#configuration

It its still not working. Provide Log from: View -> Python LSP log

**Comment by crashmeister** [comment]
1. There is no 'Python LSP log' in the 'View' menu.
2. I fixed the numeric literal and checked for others. The issue remained after correction.
3. After starting the IDE, under the 'Output' area, the 'Creating pylsp environment' tab is empty.
4. Under the 'Output' area, the 'Installing pylsp dependencies' tab contains data. See attached text file.

[pylsp_dependencies.txt](https://github.com/albilu/netbeansPython/files/14172080/pylsp_dependencies.txt)

**Comment by crashmeister** [comment]
If the 'Python LSP Log' is available in the file system somewhere, let me know where so I can find it.

If the config was the issue, the issue would NOT have corrected itself after adding/removing a space to the config.

**Comment by crashmeister** [comment]
Please note that I am using MacOS, not Windows.

Upgraded to 1.8. Copied your config above. Removed the ** from line length.
The log file is now present under 'View', but nothing ever appears inside it.
I made some deliberate syntax errors in the config and it now sometimes displays an error message under the config window. Other errors (eg: JSON Syntax) seem to appear in the IDE log.

I tried a few changes to the config but cannot get it do what I want. Example:

I changed the ignore to:
           ` "ignore": ["E114","E221","E271","E272"],`
but those rule violations are still flagged.

**All I want** is to have syntax highlighting and basic syntax checking (NOT coding rules). Is this possible ?

**Comment by crashmeister** [comment]
Found this in the IDE.log while playing with the config settings, may be why no log entries:

```
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.

```

**Comment by albilu** [comment]
@crashmeister : your problem is that your are using an empty config: "" to flake8 which override everything.

This config works well for me:
```json
"flake8": {
            "enabled": true,
            "exclude": [],
            "executable": "flake8",
            "filename": "",
            "hangClosing": false,
            "ignore": ["E501"],
            "maxLineLength": 75,
            "indentSize": 4,
            "perFileIgnores": []
        }, 
```
you need to remove:
```json
"config": "",
"select": [
                ""
            ]
```

I made a little fix so that the log is more verbose. Upgrade to version 1.9

**Comment by crashmeister** [comment]
Wow, not sure what is going on here.

1. I installed 1.9 into NB-20.
2. Removed lines as suggested.
3. Got these:

![Screenshot 2024-02-07 at 11 55 10](https://github.com/albilu/netbeansPython/assets/58121863/a08cc498-79d4-4473-84a1-3a24af23dd44)

![Screenshot 2024-02-07 at 11 56 08](https://github.com/albilu/netbeansPython/assets/58121863/66e12bf6-df8b-49ad-9d1f-4b0b8cb6bcdb)
