### ISSUE TITLE
Can't install on Netbeans 21

### ISSUE THREAD

**Issue by lhar** [albilu/netbeansPython#106]
Was reported and fixed for Netbeans 20 - now same issue on 21 - will not show on the list of available plugins  and will not install the downloaded code with the following message:

Some plugins require plugin Navigate To Test to be installed.
The plugin Navigate To Test is requested in implementation version 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655.  The following plugin is affected:       Python 
Some plugins require plugin Code Coverage Support to be installed.
The plugin Code Coverage Support is requested in implementation version 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655.  The following plugin is affected:       Python 
Some plugins require plugin Common Test Runner UI to be installed.
The plugin Common Test Runner UI is requested in implementation version 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655.  The following plugin is affected:       Python  Some plugins not installed to avoid potential installation problems.

**Comment by lhar** [comment]
Having the same issue. Any updates?

**Comment by michaelsembwever** [comment]
trying changing the version here to `RELEASE210`
rebuilding and installing the nbm under target.

i'm trying this for RELEASE220 (using the snapshot artefacts found in the mavenrepo.zip attached to each build on https://ci-builds.apache.org/job/Netbeans/job/netbeans-TLP/job/release220/ ), it builds but doesn't install (assuming sha in version mismatches, not sure yet how to build local maven snapshots artefacts from local netbeans codebase…)

@albilu , happy to sponsor you if you have the DIY recipe we're after here…

**Comment by adamtune** [comment]
Just confirming I'm experiencing the same. Sounds like it's a similar issue to 19 + 20. Thanks for all your hard work on this plugin!

**Comment by albilu** [comment]
Issue solved. Installation guide https://github.com/albilu/netbeansPython?tab=readme-ov-file#installation

**Comment by lhar** [comment]
Hi, still getting the same error with 1.9.1 and netbeans 21

**Comment by Manachi** [comment]
> Hi, still getting the same error with 1.9.1 and netbeans 21

x2

**Comment by lhar** [comment]
Hi,

 

Netbeans 22 would not start without java 17. I updated and then got this so had to disable the Python plugin:

 

Warning - could not install some modules: Python - The module Code Coverage Support was requested in implementation version "21-b15c9b7692b2764be5a997d056e2283b72ae9131" but only "22-0d0bfcf3faf364a2643238f2a44e1bb6eb8217bd" was found. Python - The module Navigate To Test was requested in implementation version "21-b15c9b7692b2764be5a997d056e2283b72ae9131" but only "22-0d0bfcf3faf364a2643238f2a44e1bb6eb8217bd" was found. Python - The module Common Test Runner UI was requested in implementation version "21-b15c9b7692b2764be5a997d056e2283b72ae9131" but only "22-0d0bfcf3faf364a2643238f2a44e1bb6eb8217bd" was found.

 



 

Thanks.

**Comment by lhar** [comment]
And when trying to activate:

 

Some plugins require plugin Navigate To Test to be installed.

The plugin Navigate To Test is requested in implementation version 21-b15c9b7692b2764be5a997d056e2283b72ae9131.  The following plugin is affected:       User Installed Plugins 

Some plugins require plugin Code Coverage Support to be installed.

The plugin Code Coverage Support is requested in implementation version 21-b15c9b7692b2764be5a997d056e2283b72ae9131.  The following plugin is affected:       User Installed Plugins 

Some plugins require plugin Common Test Runner UI to be installed.

The plugin Common Test Runner UI is requested in implementation version 21-b15c9b7692b2764be5a997d056e2283b72ae9131.  The following plugin is affected:       User Installed Plugins  Some plugins not installed to avoid potential installation problems.

 

From: Just Junk ***@***.***> 
Sent: Wednesday, June 12, 2024 12:41 PM
To: 'albilu/netbeansPython' ***@***.***>; 'albilu/netbeansPython' ***@***.***>
Cc: 'Author' ***@***.***>
Subject: RE: [albilu/netbeansPython] Can't install on Netbeans 21 (Issue #106)

 

Hi,

 

Netbeans 22 would not start without java 17. I updated and then got this so had to disable the Python plugin:

 

Warning - could not install some modules: Python - The module Code Coverage Support was requested in implementation version "21-b15c9b7692b2764be5a997d056e2283b72ae9131" but only "22-0d0bfcf3faf364a2643238f2a44e1bb6eb8217bd" was found. Python - The module Navigate To Test was requested in implementation version "21-b15c9b7692b2764be5a997d056e2283b72ae9131" but only "22-0d0bfcf3faf364a2643238f2a44e1bb6eb8217bd" was found. Python - The module Common Test Runner UI was requested in implementation version "21-b15c9b7692b2764be5a997d056e2283b72ae9131" but only "22-0d0bfcf3faf364a2643238f2a44e1bb6eb8217bd" was found.

 



 

Thanks.
