### ISSUE TITLE
Apache NetBeans 20 debian-12.5.0-amd64 Linux - Python 1.9 RELEASE-200 - hints displaying w/ no way to modify/disable them!

### ISSUE THREAD

**Issue by KastningBrandon** [albilu/netbeansPython#108]
**Description** & **Steps to reproduce the behavior:**:

I am unable to modify/disable "Hints" for Python within Apache Netbeans 20 Linux-amd64 with your Awesome Python Plugin. 

**Example Code** (Commenting within my .py File):

##### Online Source: https://www.kingjamesbibleonline.org/Revelation-11-3/

Apache NetBeans 20 Linux-amd64 "hints" highlights the code and has a dialog box that pop-ups on each line where the "caution" symbol is in Yellow that says "E266 too many leading '#' for block comment".

When I go to The Apache NetBeans 20 Linux-amd64 Menu:

Tools -> Options -> Editor Button -> Hints -> Language Dropdown Box -> (AND Python is not listed). No way of modifying/disabling These ugly and annoying hints.

**Screenshots**
![Screenshot_20240415_141407](https://github.com/albilu/netbeansPython/assets/159729115/8526ebf3-a3ed-44dd-80da-cb24e609df31)

**Desktop (please complete the following information):**
 - OS: [debian 12.5.0-amd64 Linux]
 - JDK Version [JDK-17]
- Netbeans Version: [20]
- Python Plugin Version: [1.9 (python-RELEASE200-1.9.nbm)]

Thank you again for this Awesome Python Plugin for Apache NetBeans 20 Linux-amd64

Best Regards,

Brandon Kastning

**Comment by onhae** [comment]
Netbeans Version 22, Same problem occurs.
help me please

**Comment by albilu** [comment]
Hints settings for Python are located: Tools -> Options -> Python -> Lsp Server.
To disable all hints make sure for exemple
`
plugins.autopep8.enabled=false
plugins.pycodestyle.enabled=false
`

Configure accordingly to fit your needs. Check #102 and https://github.com/python-lsp/python-lsp-server?tab=readme-ov-file#configuration for how to configure the options properly
