### ISSUE TITLE
netBeanPython plugin not Installing

### ISSUE THREAD

**Issue by AdewoyinAA** [albilu/netbeansPython#110]
Some plugins require plugin Navigate To Test to be installed.
The plugin Navigate To Test is requested in implementation version 20-91f9ed846ac143b52d50b5ea323a42c2f7e78392.  The following plugin is affected:       Python 
Some plugins require plugin Code Coverage Support to be installed.
The plugin Code Coverage Support is requested in implementation version 20-91f9ed846ac143b52d50b5ea323a42c2f7e78392.  The following plugin is affected:       Python 
Some plugins require plugin Common Test Runner UI to be installed.
The plugin Common Test Runner UI is requested in implementation version 20-91f9ed846ac143b52d50b5ea323a42c2f7e78392.  The following plugin is affected:       Python  Some plugins not installed to avoid potential installation problems.

**Comment by albilu** [comment]
Wich Netbeans version are you using?
Which netbeansPython plugin version are you trying to install?

**Comment by Shuwiku** [comment]
I have the same issue.

![image](https://github.com/user-attachments/assets/bf07c9c3-97eb-469f-8bfc-e482a40037f0)

NetBeans
Product Version: Apache NetBeans IDE DEV (Build dev-a6911ed69cd4a120890141b18fe0369256147f68)
Java: 22.0.1; OpenJDK 64-Bit Server VM 22.0.1+8
Runtime: OpenJDK Runtime Environment 22.0.1+8

Python Plugin
Version: 1.9.1 
Author: albilu Date: 03.06.2024 
Source: python-RELEASE220-1.9.1.nbm 
Homepage: https://github.com/albilu/netbeansPython

**Comment by albilu** [comment]
@Shuwiku the plugin doesnt work with a Netbeans dev build. Please use an official release build

**Comment by Shuwiku** [comment]
Well, yes. There is only this version in Pacman, so I had to install SNAP and install Netbeans directly from there, but in the end everything worked, thanks!
