### ISSUE TITLE
Project properties are not able to save

### ISSUE THREAD

**Issue by ogroef** [albilu/netbeansPython#111]
**Description**
After installing the python plugin successfully a new "Python"-project is created.
After creating the project, the properties can be change (fe: Python platform/Run Parameters).
Changing these parameter is not the issue.
The issue is that I cannot "Save" the project.  In the "File"-menu; all "Save"-options are grayed out.

**Steps to reproduce the behavior:**
1. Install the netbeansPython plugin
2. Create a new python project
3. Edit project parameters (fe: Project description)
4. See File-menu and save options are disabled and project cannot be saved.

**Expected behavior**
When changing project properties these need to be saved.

**Screencapture mp4**
https://github.com/user-attachments/assets/71b99b10-3bb1-4d94-ba07-8a5c0fbcd648

**Desktop (please complete the following information):**
 - OS: Windows 11
 - JDK Version 17.0.2; Java HotSpot(TM) 64-Bit Server VM 17.0.2+8-LTS-86
- Netbeans Version: 22
- Python Plugin Version: RELEASE220-1.9.1

**Mandatory Logs**
[IDE.log](https://github.com/user-attachments/files/16884693/IDE.log)

**Comment by albilu** [comment]
@ogroef The project properties are automatically saved when you clicked on OK.
There is no need to File -> Save.And File -> Save is greyed as there is no unsaved files remaining.

Your new description should have been well saved, you can check that in the pyproject.toml file.

**Comment by ogroef** [comment]
I get what you are saying, but the pyproject.toml file is not updated.  When I press OK, close the project the update properties are not saved.

**Comment by albilu** [comment]
I cant reproduce your issue. Make sure the plugin is well installed: check Tools -> Options -> Python -> Lsp Server. It should look like this:
![image](https://github.com/user-attachments/assets/7c194d9a-02af-42a7-a0dc-68f3ed4e8b0b)


Also check if C:\Users\odg1218\AppData\Roaming\NetBeans\22\.pythonlsp\.venv\Scripts\python.exe exist and is runnable

**Comment by ogroef** [comment]
The lsp-server is empty for me.  I'm running Python 3.1.19.

**Comment by albilu** [comment]
> I'm running Python 3.1.19.

Minimal requirement to install the plugin is Python 3.7+. After that you can add your python 3.1 environment to use via Tools -> Options -> Python -> Python Platform

**Comment by ogroef** [comment]
@albilu
1. Uninstalled the plugin 1.9.1
2. Restarted IDE
3. Reinstalled the plugin 1.9.1
4. Restarted IDE
5. ![image](https://github.com/user-attachments/assets/18b8283d-bf52-430c-8e7e-0c392b120d81)
6. The lsp is not populated
7. **C:\Users\odg1218\AppData\Roaming\NetBeans\22.pythonlsp**.venv\Scripts\python.exe doesn't exists on my pc (The bold part exists)

**Comment by ogroef** [comment]
@albilu Finally I got it working by creating myself the .venv folder and installing all the packages into the virual envirement.  When all this has been executed the properties get saved in the project file.

I will close this issue, but it is still unclear to me how this folder (.venv) shoudl be created.  Do we need to do it manually (I followed [this post section](https://packaging.python.org/en/latest/tutorials/installing-packages/#optionally-create-a-virtual-environment)) or does the folder come along during installation of the plugin.

**Comment by albilu** [comment]
> @albilu Finally I got it working by creating myself the .venv folder and installing all the packages into the virual envirement. When all this has been executed the properties get saved in the project file.
> 
> I will close this issue, but it is still unclear to me how this folder (.venv) shoudl be created. Do we need to do it manually (I followed [this post section](https://packaging.python.org/en/latest/tutorials/installing-packages/#optionally-create-a-virtual-environment)) or does the folder come along during installation of the plugin.

The folder come along during the installation!
I suspect that you are not using the required Python version: 3.7+! As you have several multiple python installation.

`python --version` on your computer should return 3.7+ for the plugin to install properly

When reinstalling deleting the bold part should have allowed the plugin to reinstall properly!
