### ISSUE TITLE
Cannot open new Python project

### ISSUE THREAD

**Issue by jkovalsky** [albilu/netbeansPython#121]
I successfully installed RELEASE230-1.9.2 version of the [Python plugin](https://plugins.netbeans.apache.org/catalogue/?id=89) into the Apache NetBeans IDE 23 running on JDK 22.0.2 and then tried to create a new Python project. Project was created on the disk, even `main.py` file opened in the Editor, however then [several exceptions](https://github.com/user-attachments/files/17166473/Exceptions.when.creating.new.Python.project.txt) were thrown and project didn't open.

`Product Version: Apache NetBeans IDE 23
Java: 22.0.2; Java HotSpot(TM) 64-Bit Server VM 22.0.2+9-70
Runtime: Java(TM) SE Runtime Environment 22.0.2+9-70
System: Linux version 5.15.0-122-generic running on amd64; UTF-8; cs_CZ (nb)
User directory: /home/cesilko/.netbeans/23
Cache directory: /home/cesilko/.cache/netbeans/23`

**Comment by albilu** [comment]
@jkovalsky Please provide 
 - OS: [e.g. iOS]
 - Python version [e.g. 3.11.8]

and a complete IDE logs. Didn't reproduce the problem.

**Comment by jkovalsky** [comment]
I am on Linux Mint 21.1 Cinnamon 5.6.8 with Unix core 5.15.0-122-generic and I don't have any Python installed.

**Comment by albilu** [comment]
> I don't have any Python installed

@jkovalsky You should have at least Python 3.8 installed for the plugin to work.
Check https://github.com/albilu/netbeansPython?tab=readme-ov-file#requirements for all requirements

**Comment by albilu** [comment]
![image](https://github.com/user-attachments/assets/91ae252b-2e8c-4875-b04b-2ead21e043b5)

Just installed without any issue using your environment like.

- I suggest you uninstall the plugin 
- Delete /home/${user}/.netbeans/23/.pythonlsp
- And install again

If issue occur again please provide complete IDE log with dependencies installation logs.

**Comment by albilu** [comment]
> After fixing that via sudo I was able to open Python project. Thanks! You can close the ticket now.

as stated you need a working python 3 environement for the plugin to work.
If no other issue please approve the plugin in the plugin portal thanks.
