### ISSUE TITLE
IDE hangs when click on python statusbar element or inside options

### ISSUE THREAD

**Issue by Chris2011** [albilu/netbeansPython#20]
**Description**
When I click on the showed version inside the statusbar "Python 3.9.2" the whole IDE hangs and took for me couple of seconds to open the options. I can't do anything except waiting. The same happens, when I open the options and click the python section. It seems that this runs in the main thread.

**Steps to reproduce the behavior:**
1. Go to Tools -> Options
2. Click on the section Python
3. IDE and options hangs until everything was found on the system.
4. Close options
5. Click on Statusbar "Python ..."
6. Same happens here, IDE hangs and after couple of seconds options opens.

**Expected behavior**
It should open the options immediately, should show loadings on the options of Python, same for NodeJS when we click on download to download the documenation for node. So i will interact with the IDE the whole time. It should run in a separate thread to not block the whole IDE. When I click accidentally I should be able to click somewhere else.

**Desktop (please complete the following information):**
- Product Version: Apache NetBeans IDE 17

- Java: 14; OpenJDK 64-Bit Server VM 14+36-1461
- Runtime: OpenJDK Runtime Environment 14+36-1461
- System: Windows 10 version 10.0 running on amd64; Cp1252; de_DE (nb)
- Python Plugin Version: 2

**Comment by albilu** [comment]
same root cause as #25
