### ISSUE TITLE
The Statusbar element should only be there when we are in a python context

### ISSUE THREAD

**Issue by Chris2011** [albilu/netbeansPython#21]
**Is your feature request related to a problem? Please describe.**
The statusbar element for showing the python version is always visivle also when I don't have any python project open.

**Describe the solution you'd like**
For me it just make sense to just see the version when I select a python project or a python file. Otherwise it is a nonesense info for me, when I don't have a python project open.

**Describe alternatives you've considered**
Do we need such statusbar? The problem is with this feature request, when you hide/show it, it will jump be shown/hidden and the UI is not userfriendly anymore. When you click outside the context to close smth, it will jump when you remove this. So at the end, we also have this for PHP but not for C/C++ and also not for Java. I would just say get rid of it. Everything that you need to know is inside the options. Just go there, if you need to. Or inside the project properties.

**Comment by albilu** [comment]
The status bar is needed to give direct insight to which Python interpreter is in use for the current context(project/file). This is thé default behaviour in all thé major Python IDEs.
In Vscode the status label is indeed removed or added according to python files in context.

So i agree whith enhancing the status bar to behave the same. You are welcome to contribute.

**Comment by Chris2011** [comment]
IMHO, this is not needed, due to the same as I wrote for Java Ant, Maven or Gradle. We don't have it in the core so why we need this information just for python? What is the difference to Java, PHP, TypeScript, etc?

**Comment by Chris2011** [comment]
> The status bar is needed to give direct insight to which Python interpreter is in use for the current context(project/file).

But this was not intended to behave like that, right?

**Comment by albilu** [comment]
This information is provided the same way by all IDEs. Spyder IDE and Pycharm display it always wich is normal as they are only supporting Python.

In case of VScode as it is a multi language support there remove/add according to Languages in context.

It was intended to always provide the status bar! What i understood from this feature request is that you would like it to be remove/add according to project in context which i agree with considering VScode.

**Comment by Chris2011** [comment]
Yes, becuase NetBeans is also a multi language IDE. I would agree with you, if we have a distribution NetBeans Python IDE only as we had it for PHP, HTML and C++ under oracle. But for the Multi IDE, it should be context specific.
