### ISSUE TITLE
Add line numbers to config section in options

### ISSUE THREAD

**Issue by Chris2011** [albilu/netbeansPython#24]
**Is your feature request related to a problem? Please describe.**
If we have a JEditorPane with a lot of lines, it would be great to have linenumbers there liek in any other editors in NetBeans. I know, that inside of the options like fonts and colors, formatting, snippets, etc. this is also missing but I will add tickets there too so this is just what came up for your plugin.

**Describe the solution you'd like**
You can try to reuse this component: https://github.com/apache/netbeans/blob/master/ide/diff/src/org/netbeans/modules/diff/builtin/visualizer/LinesComponent.java

There is also another option, but this brings more problems with it and this here seams the correct way, they already did this for the diff editor.

**Comment by albilu** [comment]
For me it is not relevant to have line numbers in setting editors with few lines and very small editing from the user. Plus as you said it is not the case in the IDE. So better keep this aligned with the IDE  for better UX

**Comment by Chris2011** [comment]
I will make PRs to add this to the editors into the Core sooner or later. Just FYI ;).
