### ISSUE TITLE
Creating new project blocks the IDE

### ISSUE THREAD

**Issue by Chris2011** [albilu/netbeansPython#25]
**Description**
When I try to create a new Python project and go to "Next" to see the infos for the name and the folders, clicking on next blocks the IDE. When I'm on the page and change the Project Name, Project Location or anything else, it also hangs the IDE for every change in the input (also browsing to find a folder). The field "Virtual Environment" doesn't block the IDE

**Steps to reproduce the behavior:**
1. Go to File -> New Project
2. Choose Python -> Python Project
3. Click on next, IDE hangs for couple of seconds (maybe of looking for the Python version or validation the fields)
4. Try to change the name or the location via input or via browse
5. It will also block the IDE everytime something was written in the field

**Expected behavior**
No blocking

**Desktop (please complete the following information):**
 - OS: Windows 11 64 bit
 - JDK Version: OpenJDK 14
- Netbeans Version: 17
- Python Plugin Version: 2

**Mandatory Logs**
lsp_log_file is empty

**Comment by albilu** [comment]
Issue reproduced on Windows. Not noticed on Linux.
Python interpreter detection hangs a bit on Windows
A quick workaround for this is to set a default Interpreter in Python -> Python Platform so that the detection is not run every time.

Fix coming later

**Comment by Chris2011** [comment]
In general detection should be fast on windows too. When I call "where python" on CMD it is really fast. It depends on how you search for it I guess.
