### ISSUE TITLE
Why is this plugin unsigned?

### ISSUE THREAD

**Issue by NejatHakan** [albilu/netbeansPython#40]
When I try to install this plugin I get the WARNING that this plugin is unsigned.

I added a screenshot.

 - OS: Linux Mint
 - JDK Version 17
- Netbeans Version: 16
- Python Plugin Version: interestingly the netbeans install wizard shows version number "0" :-)))

Best regards Nejat
![Netbeans_16_python_plugin_unsigned](https://github.com/albilu/netbeansPython/assets/8217587/5d6e3e15-1c15-455a-85df-5e7700b6079c)

**Comment by DJManas** [comment]
I had installed today on NetBeans 19, same warning.

**Comment by albilu** [comment]
> I had installed today on NetBeans 19, same warning.
The warning is normal! Netbeans present this warning for all community based plugins either unsigned or self signed.
See more details here: https://bz.apache.org/netbeans/show_bug.cgi?id=271770

**Comment by DJManas** [comment]
Ah I see. Thanks for the info. Without this, I had thought it was working and then it broke again. Thanks again!
