### ISSUE TITLE
Installation unsuccessful: Path issue?

### ISSUE THREAD

**Issue by bernard01** [albilu/netbeansPython#44]
**Description**
After successful installation of the plugin, the platform "C:\Program Files\Python38\python.exe" is recognized when entered, but the configuration is subsequently lost.

**Steps to reproduce the behavior:**
1. Go to Tools|Options|Python|Python Platform
2. Click on 'New' and enter "C:\Program Files\Python38\python.exe" 
3. Click OK and exit the Tools applet.
4. Next time I go to the same place, there is no platform

**Expected behavior**
I expect hat I can somehow make a next step after installation. For example, I wanted to configure the LSP server which I have installed. Here, I do not know how to add the configuration because I don't know how to do it. I installed it with:
 pip install python-lsp-server

**Desktop (please complete the following information):**
 - OS: Windows 7
 - JDK Version 19.0.1
- Netbeans Version: 18
- Python Plugin Version: python-RELEASE180-1.2.nbm

[messages.log](https://github.com/albilu/netbeansPython/files/11778860/messages.log)

**Comment by albilu** [comment]
@bernard01 you do not have to install anything if the installation process completed successfuly.
From your logs i can see that the plugin installation didnt succeed as there is something wrong with the paths in your filesystem:

```
SEVERE [org.openide.util.RequestProcessor]: Error in RequestProcessor org.netbeans.modules.python.Installer$$Lambda$272/0x0000000800efec40
java.nio.file.InvalidPathException: Illegal char <:> at index 4: INFO: Could not find files for the given pattern(s).
```
After successfull installation your Tools->Python Platforms->Lsp Server should look like this:
![image](https://github.com/albilu/netbeansPython/assets/35330562/eb043df2-97fc-4c5b-b5a8-aa08cd65fb67)

if not Check the Auto Update LSP Server on startup checkbox and restart Netbeans

**Comment by bernard01** [comment]
In Tools|Options|Python
All 3 tabs "Python Platform", "Python Package Repository", "LSP Server" empty.

However, in Tools|Plugins|Installed|Show details checked
Python
Version: 1.2 Source: python-RELEASE180-1.2.nbm  
Plugin Description
netbeansPython

So I uninstall it and re-start IDE.

Then I re-install.

The plugin still listed under "Downloaded" so I don't have to add it, just install from the list.
Asks for confirmation (self-signed) Continue
The NetBeans IDE installer has successfully installed the following plugins:
Python
I choose Restart IDE Now Finish.
It's unpacking it.


In the log I get an error:

java.nio.file.InvalidPathException: Illegal char <:> at index 4: INFO: Could not find files for the given pattern(s).

I don't have the ":" character  in any paths on my computer.

Here is the log again:
[messages.log](https://github.com/albilu/netbeansPython/files/11857220/messages.log)

Still in Options|Python all tabs empty. So I check Auto Update LSP Server on startup and re-start.

Still all tabs empty, so it appears the installation was unsuccessful.

**Comment by bernard01** [comment]
I installed the latest plugin python-RELEASE190-1.4.nbm on NetBeans 19.

I am getting an error that looks the same:

SEVERE [org.openide.util.Exceptions]
java.nio.file.InvalidPathException: Illegal char <:> at index 4: INFO: Could not find files for the given pattern(s).
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
[catch] at org.netbeans.modules.python.PythonUtility.lambda$getPythonExes$1(PythonUtility.java:205)

...
[messages.log](https://github.com/albilu/netbeansPython/files/12872890/messages.log)

The tabs in the Python options are empty. No Python Platform, no Python Package Repository, no Lsp Server.

I don't know what to do.
