### ISSUE TITLE
Terminal doesn't accept input.

### ISSUE THREAD

**Issue by mmc-servel** [albilu/netbeansPython#51]
The bug was observed on NetBeans16 and 18
Steps to reproduce:
1) install Python plugin
2)Create a new project with following content:
    user_name = input("Print your name: ") 
    print("Your name is:" + user_name)
3) Run the file.

In the terminal it asks for your input but it is not possible to write anything.

(NetBeans logs report no errors/warnings.)

**Comment by albilu** [comment]
@mmc-servel Thanks for reporting this. It is fixed and will be available in next release!
