### ISSUE TITLE
Statusbar disappears when Python plugin is active

### ISSUE THREAD

**Issue by piercemar** [albilu/netbeansPython#56]
**Description**
After installing netbeansPython, the status bar in Netbeans disappears.

**Steps to reproduce the behavior:**
1) From a fresh install of Netbeans 18 (no user settings), install Python plugin
2) Restart
3) Statusbar is missing

**Expected behavior**
Statusbar should stay visible

**Screenshots**

"Fresh" Netbeans 18:
![image](https://github.com/albilu/netbeansPython/assets/22491458/eb228d0a-56a9-4f37-b518-bffcd4cb2f8c)

After Python plugin installation:
![image](https://github.com/albilu/netbeansPython/assets/22491458/d2154d4f-8b7b-4236-98c9-29ffd0caf0a4)

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2
 - JDK Version 20
- Netbeans Version: 18
- Python Plugin Version: 1.2

**Mandatory Logs**
[IDE.log](https://github.com/albilu/netbeansPython/files/11934518/IDE.log)

**Comment by albilu** [comment]
This behavior is expected since #21 
The statusbar is visible only in Python Context(python files or projects in context)

**Comment by piercemar** [comment]
Does that mean it cannot be used in mixed languages projects ?
What about other plugins in the statusbar (git-branch), and other features like notifications, background tasks progress etc. ?

**Comment by albilu** [comment]
my bad i overlooked the description.
Same issue in #44
