### ISSUE TITLE
Make it possible to give a name for the new Python platform

### ISSUE THREAD

**Issue by dejlek** [albilu/netbeansPython#57]
At the moment I have many virtual environments that I have created Python platform from. They all have the same name which makes it really hard to manage. In my humble opinion those names should be amendable.

**Comment by albilu** [comment]
You mean make the Platform Name textfield editable?
Can you please show a picture so it is clear. Thanks

**Comment by albilu** [comment]
https://github.com/albilu/netbeansPython/assets/35330562/7f156cbb-bb50-45d8-8d58-cf0583000339
