### ISSUE TITLE
files are shown as empty where they are not

### ISSUE THREAD

**Issue by damnms** [albilu/netbeansPython#64]
**Description**
i have a requirements.txt that is not empty and not modified (checked with git), but in netbeans it is  shown as empty.
it looks like as if "someone" deleted the content, but as mentioned, that file is perfectly fine.
it seems like netbeans or the python plugin somehow identify them as binary, where they should be text/ascii.
i dont have those problems in pycharm, not sure if this is a netbeans bug or a netbeansPython problem.

**Steps to reproduce the behavior:**
1. open a python project
2. open the requirements.txt

**Expected behavior**
that all deps are listed as plain ascii

**Screenshots**
![Bildschirmfoto_2023-09-11_08-35-29](https://github.com/albilu/netbeansPython/assets/40913090/745099d5-3602-48d2-a3e4-c55fb28666d9)

**Desktop (please complete the following information):**
 - OS: Fedora 38
 - JDK Version 21
- Netbeans Version: 19
- Python Plugin Version: python-RELEASE190-1.4.nbm

**Mandatory Logs**
[e.g. Netbeans stacktrace/logs: (View-> IDE Log)]
[e.g. LSP Server logs ${netbeans_userdir}/.pythonlsp/lsp_log_file] 
/!\:  (this log is cleaned at Netbeans exit)

(venv) [oli@fedora usermgmtautomation]$ ls -lah requirements.txt 
-rw-r--r--. 1 oli oli 2,7K 11. Sep 08:33 requirements.txt
(venv) [oli@fedora usermgmtautomation]$ file requirements.txt 
requirements.txt: Unicode text, UTF-16, little-endian text, with CRLF line terminators

**Comment by albilu** [comment]
> edit: just tested it and changed from UTF16 to UTF8, now it works again. so maybe its a netbeans problem

Yes seems a netbeans probleme.you can test with the plugin disabled to see if its the case. If not you can reopen this issue.
