### ISSUE TITLE
Installation incomplete: Path issue?

### ISSUE THREAD

**Issue by bernard01** [albilu/netbeansPython#71]
**Description**
After successful installation of the latest plugin python-RELEASE190-1.4.nbm on NetBeans 19.

I am getting an error:

SEVERE [org.openide.util.Exceptions]
java.nio.file.InvalidPathException: Illegal char <:> at index 4: INFO: Could not find files for the given pattern(s).
at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
at java.base/java.nio.file.Path.of(Path.java:147)
at java.base/java.nio.file.Paths.get(Paths.java:69)
[catch] at org.netbeans.modules.python.PythonUtility.lambda$getPythonExes$1(PythonUtility.java:205)

...

I don't know whether this exception is actually the main issue here. I am guessing that there are perhaps multiple problems that create a somewhat confusing situation.

Perhaps I have missed some steps in the installation?

**Steps to reproduce the behavior:**
I don't expect this to be reproducible on every system.
I downloaded the plugin and installed it. Then after re-start, I inspected the options.

**Expected behavior**
I expect that in Tools|Options|Python I see content as described on the project home page (thanks for showing the images there)

**Screenshots**
The tabs Python Platform, Python Package Repository and LSP Server are empty except what is shown in the image.
![Options](https://github.com/albilu/netbeansPython/assets/1733616/9b50a3cd-33e5-4da1-9ce2-1651efa1e389)

[messages.log](https://github.com/albilu/netbeansPython/files/12901749/messages.log)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - JDK Version 20
- Netbeans Version: 19
- Python Plugin Version: 1.4

**Mandatory Logs**
As attached

**Comment by albilu** [comment]
@bernard01 : you reported the issue earlier with Netbeans 18 #44 . Is the issue still happening in Netbeans 18 after my fix?

**Comment by bernard01** [comment]
> @bernard01 : you reported the issue earlier with Netbeans 18 #44 . Is the issue still happening in Netbeans 18 after my fix?

I don't know. I uninstalled NB 18. Only .mypy_cache remained under netbeans\bin. I renamed that dir and now I can make a new 18 installation and make a test.

Which version of the plugin do you want me to test? Do you have any additional instructions for that test?

I am quite happy to spend some time on this. As I wrote, I suspect there could be multiple issues.

**Comment by albilu** [comment]
> > @bernard01 : you reported the issue earlier with Netbeans 18 #44 . Is the issue still happening in Netbeans 18 after my fix?
> 
> I don't know. I uninstalled NB 18. Only .mypy_cache remained under netbeans\bin. I renamed that dir and now I can make a new 18 installation and make a test.
> 
> Which version of the plugin do you want me to test? Do you have any additional instructions for that test?
> 
> I am quite happy to spend some time on this. As I wrote, I suspect there could be multiple issues.

i am trying to reproduce on my side for now if i failed i will come back to you. 
What version of python you have installed on your windows 7 ? 

thanks for the tips by the way

**Comment by bernard01** [comment]
> i am trying to reproduce on my side for now if i failed i will come back to you. What version of python you have installed on your windows 7 ?

Python 3.8.10 was the last full bug fix release of Python 3.8 with binary installers.
So I have 3.8.10 now.

Installed at:
C:\Program Files\Python38

Relevant system path:
C:\Program Files\Python38\Scripts\;C:\Program Files\Python38\

I don't really know much about Python.

**Comment by albilu** [comment]
Ok so i think i have some clues. If you migrated from Netbens 18 to Netbeans 19(importing your previous userdir) you need to reinstall the pylsp dependencies because there are not imported via Netbeans import mechanism. you can do this by going to Tools -> Python -> Lsp Server 
Enable Auto Update LSP.
![image](https://github.com/albilu/netbeansPython/assets/35330562/d459c8c4-a501-494b-ba56-742241a6ecaa)

This will force the reinstallation.

This stacktrace: java.nio.file.InvalidPathException: Illegal char <:> at index 4: INFO: Could not find files for the given pattern(s).

should not affect anymore after the fix in #44 . It is just informative

Please proceed and tell if its better.

**Comment by bernard01** [comment]
All is good now. Many Thanks.

2 things:

1) I think that the computer should resolve this upgrade issue automatically. I do not understand this "Auto Update LSP Sever on startup. My scenario appears to be normal and predictable and should not cause a failure. Next time I upgrade NetBeans it might happen again.

2) I think that the exception must not happen because it is confusing. Perhaps you can change something to make it go away.

**Comment by albilu** [comment]
indeed. your two points are valid. 

The auto update is primarly to update the dependencies. In this case just happen to be a valid workaround to the problem.


> 1. I think that the computer should resolve this upgrade issue automatically. I do not understand this "Auto Update LSP Sever on startup. My scenario appears to be normal and predictable and should not cause a failure. Next time I upgrade NetBeans it might happen again.

yes it will definitively happen. You can apply same workaround for now

> 2\. I think that the exception must not happen because it is confusing. Perhaps you can change something to make it go away.

This one should be ok in next release
