### ISSUE TITLE
Python not found !

### ISSUE THREAD

**Issue by BaybarsA** [albilu/netbeansPython#81]
I have downloaded phyton plugin. I opened new python project and a file. After writing a small code I clicked the run button and I got "python bulunamad"message.  Which is in Turkish but my OS in English . I tried the uninstalling and re-downloading the plugin several times but nothing changed.

Screenshots :
![pythonSS0](https://github.com/albilu/netbeansPython/assets/150463711/e90f7305-6b7d-47ca-8be9-3ec53f489eff)
![pythonSS1](https://github.com/albilu/netbeansPython/assets/150463711/8670f15a-bab4-4103-aa99-5c74979a7996)
![pythonSS2](https://github.com/albilu/netbeansPython/assets/150463711/b1eebd39-8e54-4f91-9c87-e030a02ac450)

My system : 
- OS: [Windows 10]
- JDK Version [11]
- Netbeans Version: [19]
- Python Plugin Version: I have downloaded the one only pyhton plugin in the plugins menu

**Comment by albilu** [comment]
Make sûre you have python installed on your computer. https://www.python.org/downloads/
