### ISSUE TITLE
Incompatible with netbeans 20

### ISSUE THREAD

**Issue by ruirigel** [albilu/netbeansPython#88]
I try install netbeansPython plugin in a fresh install of netbeans 20  but it fails:

```
Some plugins require plugin Navigate To Test to be installed.
The plugin Navigate To Test is requested in implementation version 19-ba85468772292fd64f188f4022f9d49f77f00b89.  The following plugin is affected:       Python 
Some plugins require plugin Code Coverage Support to be installed.
The plugin Code Coverage Support is requested in implementation version 19-ba85468772292fd64f188f4022f9d49f77f00b89.  The following plugin is affected:       Python 
Some plugins require plugin Common Test Runner UI to be installed.
The plugin Common Test Runner UI is requested in implementation version 19-ba85468772292fd64f188f4022f9d49f77f00b89.  The following plugin is affected:       Python  Some plugins not installed to avoid potential installation problems.
```

Thank you

**Comment by tatwww** [comment]
hi @albilu

Is it possible to use an older version to solve this problem? For example, netbeans 19

**Comment by gonzalo-ubiqua** [comment]
Hi there!
I was wondering if you could provide an estimate on when the modification will be ready. I appreciate your hard work on this, and I'm looking forward to the update.
Thank you!

**Comment by albilu** [comment]
@gonzalo-ubiqua Just released, will be available in the IDE in a couple of days or you can directly download here https://github.com/albilu/netbeansPython/releases. 
PS:I don't always have the time to work on this project. If you like my work consider supporting it by buying me a cup of coffee https://github.com/sponsors/albilu. 
Thanks for the feedback

**Comment by aonghus-mor** [comment]
It looks like this same assue is now arising with Netbeans 21
