### ISSUE TITLE
Error of module pynguin from LSP Server after fresh install.

### ISSUE THREAD

**Issue by DKnoto** [albilu/netbeansPython#91]
**Description:**
After installing the netbeansPython module, the LSP Server configuration shows an error in the pynguin module. Unfortunately, the error output of the LSP Sever environment shows nothing. After manually installing this module and restarting the IDE, everything is as it should be.

**Steps to reproduce the behavior:**
1. Install netbeansPython;
2. Enter into Python options;
3. Enter into LSP Server options;
4. Manualy install pynguin;
5. Restart IDE;
6. Repeat steps 2 and 3.

**Expected behavior:**
All required modules should be installed correctly.

**Screenshots:**
1.First look
![netbeansPython-1 5-LSP-pynguin-Ac128](https://github.com/albilu/netbeansPython/assets/1998807/bf73c55f-04d3-483f-8cbf-67877822fc00)

2. Output log is empty
![netbeansPython-1 5-LSP-pynguin-Bc128](https://github.com/albilu/netbeansPython/assets/1998807/cc3d7a43-bcfb-49d1-8601-727a6f3cb2c8)

3. Manual install
![netbeansPython-1 5-LSP-pynguin-Cc128](https://github.com/albilu/netbeansPython/assets/1998807/6fdf5626-919b-440b-a044-9f17b0b007f9)

5. After IDE restart all is ok
![netbeansPython-1 5-LSP-pynguin-Dc128](https://github.com/albilu/netbeansPython/assets/1998807/38734702-8116-4fa6-b6e7-110b0996b861)

**Desktop:**
 - OS: Linux Fedora 37 ppc64le 6.5.12-100
 - JDK Version: OpenJDK 17.0.8+7
- Netbeans Version: 19
- Python Plugin Version: 1.5

**Comment by albilu** [comment]
@DKnoto this is normal. I have made Pynguin optional since it has some compatibility issues with recent python versions. see https://github.com/albilu/netbeansPython/issues/70#issuecomment-1776612618 

Although i agree that the error icon is a bit misleading. Should have been a warning icon. I fixed this

**Comment by DKnoto** [comment]
Thanks a lot for the explanation :-)
