### ISSUE TITLE
Incorrect examples in the default LSP Server configuration.

### ISSUE THREAD

**Issue by DKnoto** [albilu/netbeansPython#92]
**Description:**
Incorrect examples in the default configuration of the LSP server cause errors that are difficult to detect. Removing them for a person with little experience in Apache NetBeans can cause a lot of frustration.

**Steps to reproduce the behavior:**
1. Make a fresh installation of netbeansPython;
2. Set the right margin to 120 characters, Options/Editor/Formatting/RightMargin [120];
3. Make a fresh project e.g. PythonProject1;
4. Edit main.py;
5. Add "Lorem ipsum dolor … est laborum." in line 7, print function;

![netbeansPython-1 5-Line-to-Long-A-c128](https://github.com/albilu/netbeansPython/assets/1998807/db423623-3754-4817-86f5-29a34a66fb18)

6. Check the line length configurations in the LSP server:

![netbeansPython-1 5-Line-to-Long-B-c128](https://github.com/albilu/netbeansPython/assets/1998807/fd1e4eaf-fd61-4fd3-8ff5-9685d86a6a98)

![netbeansPython-1 5-Line-to-Long-C-c128](https://github.com/albilu/netbeansPython/assets/1998807/9e08d4cf-7119-4d76-bd4b-0dc23e51ea10)

![netbeansPython-1 5-Line-to-Long-D-c128](https://github.com/albilu/netbeansPython/assets/1998807/95181d1b-0d00-4ea5-a0e2-09f140b9b9d9)

Unfortunately, we have two different forms and three different values. The inscriptions representing the number prevail.

6. I set the desired length by selecting the majority form:

![netbeansPython-1 5-Line-to-Long-E-c128](https://github.com/albilu/netbeansPython/assets/1998807/886c5e9c-2abd-43eb-9ff2-5206216a0bec)

7. The effect in the editor seems to be correct, the warnings disappear:

![netbeansPython-1 5-Line-to-Long-F-c128](https://github.com/albilu/netbeansPython/assets/1998807/9818dd76-2896-414a-82ad-1586bf7d0e8e)

8. Just to be sure, I check if a warning appears if I exceed the new length, which is 120 characters:

![netbeansPython-1 5-Line-to-Long-G-c128](https://github.com/albilu/netbeansPython/assets/1998807/23b137cc-5d85-4a51-86c1-b829c0b60ea0)

And here is the problem, the setting is not correct. We are looking for an error message.

9. Unfortunately, the error window of the LSP server environment is empty:

![netbeansPython-1 5-Line-to-Long-H-c128](https://github.com/albilu/netbeansPython/assets/1998807/03efe1bb-8284-4cd0-ae11-544027010daf)

10. Fortunately, a log and the cause of the error can be found in the configuration directory of the LSP server:

![netbeansPython-1 5-Line-to-Long-I-c128](https://github.com/albilu/netbeansPython/assets/1998807/03d33bb8-6c9f-4331-a3b4-038bf2c26788)

11. We correct the string "120" to the number 120:

![netbeansPython-1 5-Line-to-Long-J-c128](https://github.com/albilu/netbeansPython/assets/1998807/e56330d0-85f6-431f-877e-e1edde7cf14f)

12. And eventually we achieve the desired effect:

![netbeansPython-1 5-Line-to-Long-K-c128](https://github.com/albilu/netbeansPython/assets/1998807/f302a22c-b1b9-4082-8350-851f483cea57)

**Expected behavior:**

Numeric values in the default LSP configuration should be stored as numbers. Ideally, a validation of this configuration should be done before closing the dialog and informing the user of any errors. The LSP server logs should be visible in the corresponding IDE output window.

**Desktop:**
 - OS: Linux Fedora 37 ppc64le 6.5.12-100
 - JDK Version: OpenJDK 17.0.8+7
- Netbeans Version: 19
- Python Plugin Version: 1.5

**Comment by albilu** [comment]
Thanks for the detailed explanation. There is now a new Action to smoothly display the Lsp Log: View -> Python Lsp Log.
And The config will be validate prior to saving
![image](https://github.com/albilu/netbeansPython/assets/35330562/a5b71f8a-6c83-4073-976e-ea39ade695f9)
