### ISSUE TITLE
debug python input()  some error 

### ISSUE THREAD

**Issue by tatwww** [albilu/netbeansPython#96]
HI @albilu 

Below is my code, it is a simple printing program, but when I use the debug function, I cannot enter the counter, or maybe I don't understand the function. Can you help me, I use netbeans 19 + python plugin 1.5

`
import string

try:
    inputSize = int(input("Enter size of pattern: "))
except ValueError:
    print("Size of pattern must be an integer, try again.")
    quit()

if inputSize < 0:
    print("Size of pattern can't be less than or equal to 0 , try again")
    quit()

for currentLayel in range(inputSize):

    for inlineElement in range(inputSize):
    
            # 0-3 loop
            # 3               3            1
        if inlineElement >= inputSize - currentLayel:
            index = currentLayel + inlineElement
            print(string.digits[index % 10], end="")
        else:
            print("*", end="")
        
    print("")
`
![image](https://github.com/albilu/netbeansPython/assets/146701714/dfad5ab6-6487-468f-b89e-c1a575613fee)

**Comment by albilu** [comment]
@tatwww the function is working well.Its an issue with the debugger. This is a very lite version of the debugger planned to be replaced later and all features are not supported for now. This could be fixed in a later version
